# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ec5a9e1549caf28151a11d2ad3c02b56aa5553a4eb18e6df418868717f0ae6c58f66cdf103a8c03e2cd3ef37cbdba78378710d897dac22d53060f4bc007b39

test:
  secret_key_base: 79cf9f6ea7b34faa5d5929f79e4d870e8e3294583ae445182e95e6b6031bd7bd7dbd06d6b7a8191feb3988d366d8c54f66d059b9053cab1f9dd847ca96335b69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
